function navstrct = z12eph(fideph,noeph);
%Z12EPH   Reads noeph binary Z12 ephemerides and stores them in
%	      structure navstrct.

%  Written by Kai Borre
%  March 10, 2003

GPS_pi = 3.1415926535898; 	 % Exact GPS value for pi


for i = 1:noeph
% Units are either seconds, meters, or radians
A = fread(fideph,1,'char');  
if feof(fideph) == 1, break, end;
B = fread(fideph,1,'ushort');
C = fread(fideph,1,'long');
D = fread(fideph,1,'float');
E = fread(fideph,2,'long');
F = fread(fideph,3,'float');
G = fread(fideph,1,'long');
H = fread(fideph,1,'float'); 
I = fread(fideph,3,'double'); 
J = fread(fideph,1,'long');
K = fread(fideph,6,'float');
L = fread(fideph,3,'double'); 
M = fread(fideph,2,'float'); 
N = fread(fideph,1,'short');
O = fread(fideph,2,'ushort');
%Each ephemeris contains 129 bytes

navstrct(i) = struct('svprn',A,...
    'wn',B,...
    't0c',C,...
    'tgd',D,...
    'aodc',E(1),...
    'toc',E(2),...
    'af2',F(1),...
    'af1',F(2),...
    'af0',F(3),...
    'aode',G,...
    'deltan',H*GPS_pi,...
    'M0',I(1)*GPS_pi,...
    'ecc',I(2),...
    'roota',I(3),...
    'toe',J,...
    'cic',K(1),...
    'crc',K(2),...
    'cis',K(3),...
    'crs',K(4),...
    'cuc',K(5),...
    'cus',K(6),...
    'Omega0',L(1)*GPS_pi,...
    'omega',L(2)*GPS_pi,...
    'i0',L(3)*GPS_pi,...
    'Omegadot',M(1)*GPS_pi,...
    'idot',M(2)*GPS_pi,...
    'accuracy',N,...
    'health',O(1),...
    'fit',O(2));
end
%%%%%%%%% end z12eph.m %%%%%%%%%
